import Footer from '@/components/Footer';
import { NextPage } from 'next';
import Head from 'next/head';

import ThingCard from '@/components/Home/ThingCard';
import clsx from 'clsx';

// eslint-disable-next-line no-unused-vars
const Home: NextPage = (props) => (
  <>
    <Head>
      <title>Rent Thing Now</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className={
      clsx([
        'grid',
        'grid-flow-row-dense',
        'md:grid-cols-2',
        'lg:grid-cols-3',
        'xl:grid-cols-4',
        'sm:mx-auto',
        'max-w-screen-2xl',
        'my-8'
      ])
    }>
      <ThingCard
        thing={{
          name: 'Thing Name',
          description: 'Thing Description',
          image: 'https://loremflickr.com/640/640',
          price: 100,
          owner: {
            name: 'User Name',
            image: 'https://loremflickr.com/640/640',
          },
        }}
      />
    </div>
  </>
);

export default Home;
