import { NextPage } from 'next';
import Head from 'next/head';

import ThingCard from '@/components/Home/ThingCard';
import clsx from 'clsx';
import trpc from '@/utils/trpc';

// eslint-disable-next-line no-unused-vars
const Home: NextPage = (props) => {
  const { data } = trpc.allThings.useQuery();

  return (
    <>
      <Head>
        <title>Rent Thing Now</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <div className={
        clsx([
          'grid',
          'grid-flow-row-dense',
          'md:grid-cols-2',
          'lg:grid-cols-3',
          'xl:grid-cols-4',
          'sm:mx-auto',
          'max-w-screen-2xl',
          'my-8',
        ])
      }
      >
        {data?.map((thing) => (
          <ThingCard
            key={thing.id}
            thing={thing}
          />
        ))}
      </div>
    </>
  );
};

export default Home;
